[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
include_ext = ["go", "yaml"]
exclude_dir = ["vendor", "tmp"]
log = "build-errors.log"

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
