version: '3.8'

services:
  localstack:
    image: localstack/localstack:2.3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init-localstack.sh:/docker-entrypoint-initaws.d/init-localstack.sh

  imgproxy:
    image: ghcr.io/imgproxy/imgproxy:latest
    ports:
      - "8082:8080"
    environment:
      - IMGPROXY_BIND=:8080

  # app:
  #   build: .
  #   env_file: .env.test
  #   environment:
  #     - AWS_ACCESS_KEY_ID=test
  #     - AWS_SECRET_ACCESS_KEY=test
  #   ports:
  #     - "8080:8080"
  #     - "8081:8081"
  #   depends_on:
  #     localstack:
  #       condition: service_healthy
